# -*- coding: utf-8 -*-
"""data_analysis_vis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gumghWS5QFbxeD7yPZdHRUPhGsqk7FIt
"""

#Install dependencies
!pip install rasterio xarray rioxarray matplotlib numpy pandas -q

#Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Import libraries
import os
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import rasterio
import xarray as xr
import rioxarray

#Define data directory and list files
data_dir = '/content/drive/MyDrive/GEE_LST_Exports'

files = sorted(os.listdir(data_dir))
print('Files in GEE_LST_Exports:')
for f in files:
    print(f' {f}')

#Define file paths

# MODIS LST files (1km resolution)
summer_path  = f'{data_dir}/LST_Summer_Mean_2020_2025.tif'
winter_path  = f'{data_dir}/LST_Winter_Mean_2020_2025.tif'
anomaly_path = f'{data_dir}/LST_Anomaly_2023.tif'
kozan_path   = f'{data_dir}/LST_Kozan_Summer_2020_2025.tif'

# Landsat LST files (30m resolution)
ls_summer_path = f'{data_dir}/Landsat_LST_Summer_2020_2025.tif'
ls_winter_path = f'{data_dir}/Landsat_LST_Winter_2020_2025.tif'
ls_kozan_path  = f'{data_dir}/Landsat_LST_Kozan_Summer_2020_2025.tif'

print('File paths defined.')

#Read GeoTIFF files and print statistics
def read_tif(path):
    """Read a GeoTIFF file, replace NoData with NaN, print basic stats."""
    with rasterio.open(path) as src:
        data = src.read(1).astype(float)
        profile = src.profile
        nodata = src.nodata
        if nodata is not None:
            data[data == nodata] = np.nan
        print(f'File : {os.path.basename(path)}')
        print(f'  Size : {src.width} x {src.height} px')
        print(f'  CRS  : {src.crs}')
        print(f'  Min  : {np.nanmin(data):.2f} °C')
        print(f'  Max  : {np.nanmax(data):.2f} °C')
        print(f'  Mean : {np.nanmean(data):.2f} °C')
        print()
    return data, profile

# Read all files
summer_data,    summer_profile    = read_tif(summer_path)
winter_data,    winter_profile    = read_tif(winter_path)
anomaly_data,   anomaly_profile   = read_tif(anomaly_path)
kozan_data,     kozan_profile     = read_tif(kozan_path)
ls_summer_data, ls_summer_profile = read_tif(ls_summer_path)
ls_winter_data, ls_winter_profile = read_tif(ls_winter_path)
ls_kozan_data,  ls_kozan_profile  = read_tif(ls_kozan_path)

#Visualization MODIS LST layers
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

im1 = axes[0, 0].imshow(summer_data, cmap='RdYlBu_r', vmin=25, vmax=50)
axes[0, 0].set_title('MODIS LST — Summer Mean (2020-2025)')
plt.colorbar(im1, ax=axes[0, 0], label='°C')

im2 = axes[0, 1].imshow(winter_data, cmap='RdYlBu_r', vmin=0, vmax=20)
axes[0, 1].set_title('MODIS LST — Winter Mean (2020-2025)')
plt.colorbar(im2, ax=axes[0, 1], label='°C')

im3 = axes[1, 0].imshow(anomaly_data, cmap='RdBu_r', vmin=-5, vmax=5)
axes[1, 0].set_title('MODIS LST — Anomaly 2023 vs Long-term Mean')
plt.colorbar(im3, ax=axes[1, 0], label='°C')

im4 = axes[1, 1].imshow(kozan_data, cmap='RdYlBu_r', vmin=25, vmax=50)
axes[1, 1].set_title('MODIS LST — Kozan Summer Mean (2020-2025)')
plt.colorbar(im4, ax=axes[1, 1], label='°C')

plt.tight_layout()
plt.savefig(f'{data_dir}/modis_lst_overview.png', dpi=150)
plt.show()
print('MODIS overview saved.')

#Visualization Landsat layers
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

im5 = axes[0].imshow(ls_summer_data, cmap='RdYlBu_r', vmin=25, vmax=50)
axes[0].set_title('Landsat LST — Summer Mean (2020-2025)')
plt.colorbar(im5, ax=axes[0], label='°C')

im6 = axes[1].imshow(ls_winter_data, cmap='RdYlBu_r', vmin=0, vmax=20)
axes[1].set_title('Landsat LST — Winter Mean (2020-2025)')
plt.colorbar(im6, ax=axes[1], label='°C')

im7 = axes[2].imshow(ls_kozan_data, cmap='RdYlBu_r', vmin=25, vmax=50)
axes[2].set_title('Landsat LST — Kozan Summer Mean (2020-2025)')
plt.colorbar(im7, ax=axes[2], label='°C')

plt.tight_layout()
plt.savefig(f'{data_dir}/landsat_lst_overview.png', dpi=150)
plt.show()
print('Landsat overview saved.')

#Resolution comparison : MODIS vs Landsat
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# MODIS Summer
im1 = axes[0].imshow(summer_data, cmap='RdYlBu_r', vmin=25, vmax=50)
axes[0].set_title('MODIS LST — Summer (1km resolution)')
plt.colorbar(im1, ax=axes[0], label='°C')

# Landsat Summer
im2 = axes[1].imshow(ls_summer_data, cmap='RdYlBu_r', vmin=25, vmax=50)
axes[1].set_title('Landsat LST — Summer (30m resolution)')
plt.colorbar(im2, ax=axes[1], label='°C')

plt.suptitle('Spatial Resolution Comparison: MODIS vs Landsat', fontsize=14)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/GEE_LST_Exports/modis_vs_landsat.png', dpi=150)
plt.show()
print('Resolution comparison saved.')

# Load and inspect monthly time series CSV
csv_path = f'{data_dir}/MODIS_LST_Monthly_Timeseries.csv'
df = pd.read_csv(csv_path, parse_dates=['date'])
df = df[['date', 'year', 'month', 'LST_mean']].sort_values('date').reset_index(drop=True)

print(f'Rows     : {len(df)}')
print(f'Date range: {df["date"].min()} → {df["date"].max()}')
print(f'LST range : {df["LST_mean"].min():.2f} — {df["LST_mean"].max():.2f} °C')
print()
print(df.head(12))

#Missing value check and interpolation

# Build a complete monthly date index (2020-01 to 2024-12)
all_dates = pd.date_range(start='2020-01-01', end='2024-12-01', freq='MS')
df_full = pd.DataFrame({'date': all_dates})
df_full = df_full.merge(df[['date', 'LST_mean']], on='date', how='left')

missing_count = df_full['LST_mean'].isna().sum()
print(f'Missing months: {missing_count}')

if missing_count == 0:
    print('No missing values.')
    print('Linear and cubic columns are added for consistency.')

# Apply interpolation regardless
df_full['LST_linear'] = df_full['LST_mean'].interpolate(method='linear')
df_full['LST_cubic']  = df_full['LST_mean'].interpolate(method='cubic')

print(df_full.head(12))

# Time series visualization

fig, axes = plt.subplots(2, 1, figsize=(14, 10))

# Upper panel: raw data and interpolation curves
axes[0].plot(df_full['date'], df_full['LST_mean'],
             'o', color='black', label='Monthly Mean LST', markersize=4)
axes[0].plot(df_full['date'], df_full['LST_linear'],
             '-', color='steelblue', label='Linear Interpolation', linewidth=1.5)
axes[0].plot(df_full['date'], df_full['LST_cubic'],
             '--', color='tomato', label='Cubic Interpolation', linewidth=1.5)
axes[0].set_title('MODIS LST Monthly Time Series (2020–2024)')
axes[0].set_ylabel('LST (°C)')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Lower panel: mean seasonal cycle
monthly_mean = df_full.groupby(df_full['date'].dt.month)['LST_mean'].mean()
colors = plt.cm.RdYlBu_r(monthly_mean.values / monthly_mean.max())
axes[1].bar(monthly_mean.index, monthly_mean.values, color=colors)
axes[1].set_title('Mean Seasonal LST Cycle (2020–2024)')
axes[1].set_xlabel('Month')
axes[1].set_ylabel('LST (°C)')
axes[1].set_xticks(range(1, 13))
axes[1].set_xticklabels(['Jan','Feb','Mar','Apr','May',
                          'Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
axes[1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig(f'{data_dir}/lst_timeseries_interpolation.png', dpi=150)
plt.show()
print('Time series visualization saved.')

#xarray: load summer LST as labeled array

# Load MODIS summer GeoTIFF as xarray DataArray for downstream use
da_summer = rioxarray.open_rasterio(summer_path).squeeze()
da_summer = da_summer.where(da_summer != da_summer.attrs.get('_FillValue', -9999))
da_summer.name = 'LST_Summer'

print(da_summer)
print(f'\nMean LST (xarray): {float(da_summer.mean()):.2f} °C')

# Convert GeoTIFF to PNG for CesiumJS overlay

output_dir = f'{data_dir}/cesium_overlays'
os.makedirs(output_dir, exist_ok=True)

def tif_to_png(data, output_path, vmin, vmax, cmap='RdYlBu_r'):
    """Normalize GeoTIFF data and save as PNG for Cesium overlay."""
    # Normalize to 0-1
    normalized = (data - vmin) / (vmax - vmin)
    normalized = np.clip(normalized, 0, 1)

    # Apply colormap
    colormap = matplotlib.colormaps[cmap]
    rgba = colormap(normalized)

    # Replace NaN with transparent
    rgba[np.isnan(data)] = [0, 0, 0, 0]

    # Save as PNG
    plt.imsave(output_path, rgba)
    print(f'Saved: {os.path.basename(output_path)}')

# Convert all layers
tif_to_png(summer_data,  f'{output_dir}/lst_summer.png',  vmin=25, vmax=50)
tif_to_png(winter_data,  f'{output_dir}/lst_winter.png',  vmin=0,  vmax=20)
tif_to_png(anomaly_data, f'{output_dir}/lst_anomaly.png', vmin=-5, vmax=5, cmap='RdBu_r')
tif_to_png(kozan_data,   f'{output_dir}/lst_kozan.png',   vmin=25, vmax=50)

print('\nAll PNG overlays saved to:', output_dir)