# -*- coding: utf-8 -*-
"""fire_risk_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bu8fREU0KhkMFaeaJ_ocd5Rfj2B4n5rq
"""

!pip install imbalanced-learn scikit-learn torch -q

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")


from collections import Counter
import warnings
warnings.filterwarnings("ignore")

import os

data_dir = '/content/drive/MyDrive/GEE_LST_Exports'
train_df = pd.read_csv(f'{data_dir}/Kozan_Fire_Risk_Dataset.csv')

train_df.columns

train_df.head()

train_df.describe()

"""# Variable Description
  1. system:index : Automatically assigned row ID by GEE — not used in the model
  1. BSI: Bare Soil Index — high = less vegetation → higher fire risk
  2. EVI: Enhanced Vegetation Index — more sensitive than NDVI
  3. LST_C: Land Surface Temperature from Landsat (°C) — 30 m resolution
  4. MODIS_LST: Land Surface Temperature from MODIS (°C) — 1 km resolution
  5. NBR: Normalized Burn Ratio — decreases after fire
  6. NDVI: Normalized Difference Vegetation Index — high = dense vegetation, low = bare soil
  7. NDWI: Water / Moisture Index — low = dry area → higher fire risk
  8. SAVI: Soil Adjusted Vegetation Index — reduces soil effect, suitable for agricultural areas
  9. aspect: Aspect (degrees) — south-facing slopes tend to be drier
  10. elevation: Elevation (Elevation in meters) — derived from DEM
  11. fire_label: Target variable — 1 = fire present, 0 = no fire
  12. month: Month (1–12) — used for seasonality
  13. slope: Slope (degrees) — steeper slopes accelerate fire spread
  14. .geo: Coordinate information (empty) — not used in the model
"""

train_df.info()

"""# Univariate Variable Analysis
Categorical Variable: system:index, .geo

Numerical Variable: BSI, EVI, LST_C, MODIS_LST, NBR, NDVI, NDWI, SAVI, aspect, elevation, fire_label, month, slope
"""

# Categorical variable analysis with bar plot — fire_label and month
def plot_bar(variable):
    plt.figure(figsize=(9, 3))
    df_temp = train_df[variable].value_counts()
    plt.bar(df_temp.index, df_temp.values)
    plt.xlabel(variable)
    plt.ylabel("Count")
    plt.title(f"{variable} distribution")
    plt.xticks(df_temp.index)
    plt.show()
    print(f"{variable}:\n{df_temp}\n")

categorical_var = ["fire_label", "month"]
for c in categorical_var:
    plot_bar(c)

# Numerical variable analysis with histogram
def plot_hist(variable):
  plt.figure(figsize = (9,3))
  plt.hist(train_df[variable], bins = 50)
  plt.xlabel(variable)
  plt.ylabel("Frequency")
  plt.title("{} distribution with hist".format(variable))
  plt.show()

numerical_var = ["BSI", "EVI", "LST_C", "MODIS_LST", "NBR", "NDVI", "NDWI", "SAVI", "aspect", "elevation", "slope"]
for n in numerical_var:
  plot_hist(n)

# Group analysis according to fire label
print("Fire Label Distribution")
print(train_df["fire_label"].value_counts())
print(f"\nFire ratio: {train_df['fire_label'].mean():.2f}")

# Average of each attribute according to fire_labelı
print("\nMean values by fire_label")
print(train_df.groupby("fire_label")[numerical_var].mean().T)

# Correlation matrix
plt.figure(figsize=(12, 10))
correlation_features = numerical_var + ['fire_label'] # Include 'fire_label' for correlation
corr = train_df[correlation_features].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="RdYlBu_r",
            center=0, square=True, linewidths=0.5)
plt.title("Feature Correlation Matrix")
plt.tight_layout()
plt.savefig(f'{data_dir}/correlation_matrix.png', dpi=150)
plt.show()

print("\nCorrelation with fire_label")
print(corr["fire_label"].sort_values(ascending=False))

# Outlier detection with IQR method
def detect_outliers(df, features):
    outlier_indices = []
    for col in features:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        outliers = df[(df[col] < lower) | (df[col] > upper)].index
        outlier_indices.extend(outliers)
        print(f"{col}: {len(outliers)} outlier "
              f"(lower={lower:.2f}, upper={upper:.2f})")
    return list(Counter(outlier_indices).keys())

feature_cols = ["BSI", "EVI", "LST_C", "MODIS_LST", "NBR",
                "NDVI", "NDWI", "SAVI", "aspect", "elevation", "slope"]

print("Outlier Detection (IQR)")
outlier_idx = detect_outliers(train_df, feature_cols)
print(f"\nTotal outlier counts: {len(outlier_idx)}")

# Visualization with box plot
fig, axes = plt.subplots(3, 4, figsize=(18, 12))
axes = axes.flatten()
for i, col in enumerate(feature_cols):
    axes[i].boxplot(train_df[col].dropna())
    axes[i].set_title(col)
    axes[i].grid(True, alpha=0.3)
plt.suptitle("Outlier Detection — Boxplots", fontsize=14)
plt.tight_layout()
plt.savefig(f'{data_dir}/outlier_boxplots.png', dpi=150)
plt.show()

# Clean up outliers
train_df_clean = train_df.drop(outlier_idx).reset_index(drop=True)
print(f"\nOriginal: {len(train_df)} → Cleaned up: {len(train_df_clean)}")

# Missing Value analysis
print("Missing Values")
missing = train_df_clean.isnull().sum()
missing_pct = (missing / len(train_df_clean)) * 100
missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_pct
}).sort_values('Missing %', ascending=False)
print(missing_df[missing_df['Missing Count'] > 0])

# Fillng missing values with median
for col in feature_cols:
    if train_df_clean[col].isnull().sum() > 0:
        median_val = train_df_clean[col].median()
        train_df_clean[col].fillna(median_val, inplace=True)
        print(f"{col}: filled with {median_val:.2f} ")

print("\nNumber of missing values")
print(train_df_clean.isnull().sum().sum())

# Fire vs Non-fire
fig, axes = plt.subplots(3, 4, figsize=(18, 12))
axes = axes.flatten()

for i, col in enumerate(feature_cols):
    axes[i].hist(train_df_clean[train_df_clean['fire_label']==0][col],
                 bins=30, alpha=0.6, color='steelblue', label='Non-fire')
    axes[i].hist(train_df_clean[train_df_clean['fire_label']==1][col],
                 bins=30, alpha=0.6, color='tomato', label='Fire')
    axes[i].set_title(col)
    axes[i].legend(fontsize=8)
    axes[i].grid(True, alpha=0.3)

plt.suptitle("Feature Distributions: Fire vs Non-fire", fontsize=14)
plt.tight_layout()
plt.savefig(f'{data_dir}/feature_distributions.png', dpi=150)
plt.show()

# Pairplot
key_features = ['LST_C', 'NDVI', 'NDWI', 'NBR', 'slope', 'fire_label']
sns.pairplot(train_df_clean[key_features], hue='fire_label',
             palette={0: 'steelblue', 1: 'tomato'}, plot_kws={'alpha': 0.5})
plt.suptitle("Pairplot — Key Features", y=1.02)
plt.savefig(f'{data_dir}/pairplot.png', dpi=150)
plt.show()

# Feature engineering
train_df_clean['LST_NDVI_ratio'] = train_df_clean['LST_C'] / (train_df_clean['NDVI'] + 1e-6)
train_df_clean['fire_weather_index'] = (train_df_clean['LST_C'] *
                                         (1 - train_df_clean['NDWI']) *
                                         train_df_clean['slope'])
train_df_clean['dryness'] = train_df_clean['BSI'] - train_df_clean['NDWI']
train_df_clean['LST_diff'] = train_df_clean['LST_C'] - train_df_clean['MODIS_LST']

print("New features are added:")
print(train_df_clean[['LST_NDVI_ratio', 'fire_weather_index',
                        'dryness', 'LST_diff']].describe())

# last version of RF model
import joblib
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, average_precision_score,
                             precision_recall_curve, recall_score, precision_score, f1_score)
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline # CV sızıntısını önlemek için kritik!

# Data process and scaling
final_features = ['LST_C', 'MODIS_LST', 'NDVI', 'NDWI', 'NBR', 'EVI',
                  'SAVI', 'BSI', 'elevation', 'slope', 'aspect',
                  'LST_NDVI_ratio', 'fire_weather_index', 'dryness', 'LST_diff']

X = train_df_clean[final_features].values
y = train_df_clean['fire_label'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)
print(f"Train: {len(X_train)} — Test: {len(X_test)}")

# manuel SMOTE
smote = SMOTE(random_state=42, k_neighbors=3)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

# Logistic Regression
lr = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
lr.fit(X_train_sm, y_train_sm)
y_pred_lr = lr.predict(X_test)
y_proba_lr = lr.predict_proba(X_test)[:, 1]

# Random Forest + SMOTE Pipeline + Grid Search
rf_pipeline = ImbPipeline([
    ('smote', SMOTE(random_state=42, k_neighbors=3)),
    ('rf', RandomForestClassifier(class_weight='balanced', random_state=42))
])

# Pipeline parameters
rf_params = {
    'rf__n_estimators': [100, 300],
    'rf__max_depth': [10, 15, None],
    'rf__min_samples_leaf': [1, 2]
}

rf_grid = GridSearchCV(
    rf_pipeline, rf_params, cv=5, scoring='recall', n_jobs=-1, verbose=0
)
# ATTENTION: We are now providing the original data (X_train), not the SMOTE-applied data (X_train_sm)!
# SMOTE will only be automatically applied to the training sections within the CV folds.
rf_grid.fit(X_train, y_train)
print(f"\nRF Best params: {rf_grid.best_params_}")

best_rf_pipeline = rf_grid.best_estimator_
y_pred_rf    = best_rf_pipeline.predict(X_test)
y_proba_rf   = best_rf_pipeline.predict_proba(X_test)[:, 1]

# XGBoost
# scale_pos_weight parameter for imbalanced values
pos_weight = (len(y_train) - sum(y_train)) / sum(y_train)
xgb_model = xgb.XGBClassifier(scale_pos_weight=pos_weight, random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)
y_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]

# Changing the Decision Threshold (0.50->0.35)
custom_threshold = 0.35
y_pred_rf_custom = (y_proba_rf >= custom_threshold).astype(int)

# Metrics and table
def get_metrics(y_true, y_pred, y_prob):
    return {
        'Recall': recall_score(y_true, y_pred, zero_division=0),
        'Precision': precision_score(y_true, y_pred, zero_division=0),
        'F1-Score': f1_score(y_true, y_pred, zero_division=0),
        'PR-AUC': average_precision_score(y_true, y_prob),
        'ROC-AUC': roc_auc_score(y_true, y_prob)
    }

results = {
    'LogReg (Baseline)': get_metrics(y_test, y_pred_lr, y_proba_lr),
    'RF (SMOTE + Balanced)': get_metrics(y_test, y_pred_rf, y_proba_rf),
    f'RF (Threshold={custom_threshold})': get_metrics(y_test, y_pred_rf_custom, y_proba_rf),
    'XGBoost': get_metrics(y_test, y_pred_xgb, y_proba_xgb)
}

results_df = pd.DataFrame(results).T
print("\n Model Comparison")
print(results_df.round(4))

# Precision-Recall Curve
precision_rf, recall_rf, thresholds_rf = precision_recall_curve(y_test, y_proba_rf)
precision_xgb, recall_xgb, thresholds_xgb = precision_recall_curve(y_test, y_proba_xgb)

plt.figure(figsize=(8, 6))
plt.plot(recall_rf, precision_rf, label=f'Random Forest (PR-AUC: {results["RF (SMOTE + Balanced)"]["PR-AUC"]:.3f})', color='tomato')
plt.plot(recall_xgb, precision_xgb, label=f'XGBoost (PR-AUC: {results["XGBoost"]["PR-AUC"]:.3f})', color='green')
plt.axvline(x=results[f'RF (Threshold={custom_threshold})']['Recall'], color='gray', linestyle='--', label=f'Custom Threshold ({custom_threshold})')
plt.title('Precision-Recall Curve (Trade-off)')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.legend()
plt.grid(True, alpha=0.3)
# plt.savefig(f'{data_dir}/pr_curve_comparison.png', dpi=150)
plt.show()

# Model saving
final_trained_rf = best_rf_pipeline.named_steps['rf']
joblib.dump(final_trained_rf, f'{data_dir}/fire_risk_rf_final.pkl')
joblib.dump(scaler, f'{data_dir}/scaler_final.pkl')
print('\nModel and Scaler saved.')

from sklearn.metrics import confusion_matrix
import seaborn as sns

# RF Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)

plt.figure(figsize=(6, 5))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Non-fire', 'Fire'],
            yticklabels=['Non-fire', 'Fire'])
plt.title('Random Forest — Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.savefig(f'{data_dir}/confusion_matrix_rf.png', dpi=150)
plt.show()

tn_rf, fp_rf, fn_rf, tp_rf = cm_rf.ravel()
print(f'True Positive    : {tp_rf}')
print(f'False Negative   : {fn_rf}')
print(f'False Positive   : {fp_rf}')
print(f'True Negative    : {tn_rf}')
print(f'False Negative Rate: {fn_rf/(fn_rf+tp_rf):.2%}')

# last version of mlp model

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import recall_score, precision_score, f1_score, fbeta_score
import numpy as np
import matplotlib.pyplot as plt

# GPU (CUDA) Control
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using hardware: {device}")

# Transform to Tensor & Move to Device
X_train_t = torch.FloatTensor(X_train_sm).to(device)
y_train_t = torch.FloatTensor(y_train_sm).to(device)
X_test_t  = torch.FloatTensor(X_test).to(device)

# MLP Structure
class FireRiskMLP(nn.Module):
    def __init__(self, input_dim):
        super(FireRiskMLP, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x).squeeze()

# DataLoader
train_dataset = TensorDataset(X_train_t, y_train_t)
train_loader  = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Dynamic pos_weight computation
num_positive = y_train_sm.sum()
num_negative = len(y_train_sm) - num_positive
dynamic_weight = num_negative / num_positive if num_positive > 0 else 1.0

input_dim  = X_train_sm.shape[1]
model      = FireRiskMLP(input_dim=input_dim).to(device) # Modeli GPU'ya gönder
pos_weight = torch.tensor([dynamic_weight]).to(device)  # Ağırlığı GPU'ya gönder

criterion  = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer  = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
scheduler  = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', patience=10, factor=0.5)

# Train
epochs       = 150
train_losses = []

for epoch in range(epochs):
    model.train()
    epoch_loss = 0
    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        y_pred = model(X_batch)
        loss   = criterion(y_pred, y_batch)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    avg_loss = epoch_loss / len(train_loader)
    train_losses.append(avg_loss)
    scheduler.step(avg_loss)

    if (epoch+1) % 30 == 0:
        print(f'Epoch {epoch+1}/{epochs} — Loss: {avg_loss:.4f}')

# Evaluation
model.eval()
with torch.no_grad():
    logits        = model(X_test_t)
    # CPU'ya geri çekip numpy'a çeviriyoruz çünkü scikit-learn GPU tensörü anlamaz
    y_proba_mlp   = torch.sigmoid(logits).cpu().numpy()

# Threshold Optimization (F2-Score)
print('\nMLP Threshold Optimization (Optimized for Recall via F2-Score)')
print(f'{"Threshold":<10} {"Precision":<12} {"Recall":<10} {"F2-Score"}')
print('-' * 45)

best_t   = 0.5
best_f2  = 0

for t in np.arange(0.2, 0.6, 0.05):
    y_pred_t = (y_proba_mlp >= t).astype(int)
    p = precision_score(y_test, y_pred_t, zero_division=0)
    r = recall_score(y_test, y_pred_t, zero_division=0)

    # F2-Score
    f2 = fbeta_score(y_test, y_pred_t, beta=2, zero_division=0)

    print(f'{t:.2f}        {p:.3f}        {r:.3f}      {f2:.3f}')

    if f2 > best_f2:
        best_f2 = f2
        best_t  = t

y_pred_mlp = (y_proba_mlp >= best_t).astype(int)

print(f'\nBest threshold: {best_t:.2f}')
print('\nMLP Final Results')
print(classification_report(y_test, y_pred_mlp, target_names=['Non-fire', 'Fire'], zero_division=0))

# Saving
torch.save(model.cpu().state_dict(), f'{data_dir}/fire_risk_mlp.pt')
print('MLP model saved successfully for edge deployment.')

# MLP Confusion Matrix
cm_mlp = confusion_matrix(y_test, y_pred_mlp)

plt.figure(figsize=(6, 5))
sns.heatmap(cm_mlp, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Non-fire', 'Fire'],
            yticklabels=['Non-fire', 'Fire'])
plt.title('MLP — Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.savefig(f'{data_dir}/confusion_matrix_mlp.png', dpi=150)
plt.show()

tn_mlp, fp_mlp, fn_mlp, tp_mlp = cm_mlp.ravel()
print(f'True Positive   : {tp_mlp}')
print(f'False Negative  : {fn_mlp}')
print(f'False Positive  : {fp_mlp}')
print(f'True Negative   : {tn_mlp}')
print(f'False Negative Rate: {fn_mlp/(fn_mlp+tp_mlp):.2%}')